### ISSUE TITLE
希望添加只扫描二维码或条形码等不同码的设置字段

### ISSUE THREAD

**Issue by shichuanenhui** [jenly1314/CameraScan#1]
举个例子：setBarcodeFormats(Barcode.FORMAT_QR_CODE)，只扫描二维码
                  setBarcodeFormats(Barcode.FORMAT_CODE_128)，只扫描条形码

**Comment by jenly1314** [comment]
> 举个例子：setBarcodeFormats(Barcode.FORMAT_QR_CODE)，只扫描二维码 setBarcodeFormats(Barcode.FORMAT_CODE_128)，

你提的问题与**CameraScan** 没有任何关系，看错库了吧？如果我没猜错的话，你应该说的是[MLKit](https://github.com/jenly1314/MLKit)吧，去看下 [BarcodeScanningAnalyzer](https://github.com/jenly1314/MLKit/blob/master/mlkit-barcode-scanning/src/main/java/com/king/mlkit/vision/barcode/analyze/BarcodeScanningAnalyzer.java) 的构造；如果是扫二维码，建议通过继承 [QRCodeCameraScanActivity](https://github.com/jenly1314/MLKit/blob/master/mlkit-barcode-scanning/src/main/java/com/king/mlkit/vision/barcode/QRCodeCameraScanActivity.java)  的方式实现；代码示例可参见：[QRCodeScanningActivity](https://github.com/jenly1314/MLKit/blob/master/app/src/main/java/com/king/mlkit/vision/app/barcode/QRCodeScanningActivity.kt)
