### ISSUE TITLE
关于BaseCameraScan类startCamera方法配置图像分析行为new线程池的疑问

### ISSUE THREAD

**Issue by spark7fire** [jenly1314/CameraScan#4]
疑问点的代码：
`
// 图像分析
                ImageAnalysis imageAnalysis = mCameraConfig.options(new ImageAnalysis.Builder()
                        .setOutputImageFormat(ImageAnalysis.OUTPUT_IMAGE_FORMAT_YUV_420_888)
                        .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST));
                imageAnalysis.setAnalyzer(Executors.newSingleThreadExecutor(), image -> {
                    if (isAnalyze && !isAnalyzeResult && mAnalyzer != null) {
                        mAnalyzer.analyze(image, mOnAnalyzeListener);
                    }
                    image.close();
                });
`
在BaseCameraScan类里的startCamera方法中进行配置图像分析的行为中，是直接new一个线程池给分析对象进行分析过程的，但在stopCamera方法中没有去释放这个线程池，这是否会造成资源泄露呢？

**Comment by jenly1314** [comment]
> 疑问点的代码： `// 图像分析 ImageAnalysis imageAnalysis = mCameraConfig.options(new ImageAnalysis.Builder() .setOutputImageFormat(ImageAnalysis.OUTPUT_IMAGE_FORMAT_YUV_420_888) .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)); imageAnalysis.setAnalyzer(Executors.newSingleThreadExecutor(), image -> { if (isAnalyze && !isAnalyzeResult && mAnalyzer != null) { mAnalyzer.analyze(image, mOnAnalyzeListener); } image.close(); });` 在BaseCameraScan类里的startCamera方法中进行配置图像分析的行为中，是直接new一个线程池给分析对象进行分析过程的，但在stopCamera方法中没有去释放这个线程池，这是否会造成资源泄露呢？

* 有泄露的可能；对于扫码这种场景而言，泄露的概率可忽略不计；
* 不过从代码的严谨与优雅性来说：能主动释放自然最好。（有空再优化）
